version: "3.4"
services:
  nginx:
    image: ${NGINX_IMAGE:-nginx-local-dev:alpine}
    build:
      context: ./nginx
      dockerfile: ${NGINX_DOCKERFILE:-Dockerfile}
    volumes:
      - ${PWD}/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  angular:
    build:
      context: ${PWD}/frontend
      dockerfile: ${PWD}/.docker/angular/${ANGULAR_DOCKERFILE:-Dockerfile}
    volumes:
      - ${ANGULAR_ROOT:-../frontend}:/app
      - npm_cache:/root/.npm
    command: "ng serve --disableHostCheck --host 0.0.0.0 --port 8200"
  php7fpm:
    build:
      context: ${PWD}/backend
      dockerfile: ${PWD}/.docker/php7fpm/${PHP_DOCKERFILE:-Dockerfile}
    volumes:
      - ${PWD}/backend:/app
  mysql:
    image: "mysql:5.7"
    command: mysqld --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8
    volumes:
      - mysql_datavolume:/var/lib/mysql
  phpmyadmin:
    volumes:
      - ${PWD}/.docker/phpmyadmin/config.autologin.php:/etc/phpmyadmin/config.user.inc.php
volumes:
  npm_cache:
  mysql_datavolume:
